= Ubiquiti

OpenNMS configuration files for Ubiquiti AirMax 6 & 8.

== Installation

.Download and install from GitHub
[source, bash]
----
mkdir ${HOME}/opennms-config-workspace
cd ${HOME}/opennms-config-workspace
git clone https://github.com/opennms-config-modules/ubiquiti.git
----

=== Data Collection

.Install datacollection configuration
[source, bash]
----
cp ${HOME}/opennms-config-workspace/ubiquiti/datacollection/*.xml ${OPENNMS_HOME}/etc/datacollection
----

.Include in datacollection-config.xml
[source, xml]
----
<include-collection dataCollectionGroup="Ubiquiti"/>
----

=== Graph Report Definitions

.Install graph report definitions
[source, bash]
----
cp ${HOME}/opennms-config-workspace/ubiquiti/graphs/*.properties ${OPENNMS_HOME}/etc/snmp-graph.properties.d
----

=== Monitor ===

`${home}/monitors/poller-configuration.xml` contains an example to check DFS status.

=== Thresholding ===

`${home}/thresholds/thresholds.xml` contains an example to check signal strength fluctuations.

== Grafana ==

Import dashboard https://grafana.com/dashboards/6498[6498].

== Known Issues ==

Ubiquiti does not use SNMP compliant. Therefore OpenNMS settings are necessary to collect metrics.

Create a property file:

`$ONMS_HOME/opennms.properties.d/allowSNMPv2InV1.properties`

with content:
`org.opennms.snmp.snmp4j.allowSNMPv2InV1=true`
