{
 "title": "OpenNMS Ubiquiti AirMax",
 "description": "Overview board for AirMax devices",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "nodeFilter((nodeSysOID LIKE '.1.3.6.1.4.1.10002.1' | nodeSysOID LIKE '.1.3.6.1.4.1.41112.1.4' ) & serviceName like 'SNMP')"
   },
   { "name": "station", "query": "nodeResources($node)" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Radio Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntRadioMode",
     "label": "Mode",
     "nodeId": "$node",
     "resourceId": "ubntRadioEntry[1]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Net Role",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntHostNetRole",
     "label": "TDD",
     "nodeId": "$node",
     "resourceId": "nodeSnmp[]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "AirMax Prio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntAirMaxPriority",
     "label": "Prio",
     "nodeId": "$node",
     "resourceId": "ubntAirMaxEntry[1]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "HDOP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntGpsHDOP",
     "label": "HDOP",
     "nodeId": "$node",
     "resourceId": "nodeSnmp[]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "AirSync Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntAirSyncMode",
     "label": "SyncMode",
     "nodeId": "$node",
     "resourceId": "ubntAirSyncEntry[1]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    { "expression": "FrequencyRaw / 1000", "label": "Frequency", "type": "expression" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntWlStatChanWidth",
     "label": "Bandwidth",
     "nodeId": "$node",
     "resourceId": "ubntWlStatEntry[1]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "filter": {
      "backend": "Java",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
      "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
      "name": "Chomp",
      "parameter": [
       {
        "default": "true",
        "description": "When set, leading and trailing rows containing NaNs will be removed",
        "displayName": "Strip",
        "key": "stripNaNs",
        "required": false,
        "type": "boolean"
       },
       {
        "default": "0",
        "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
        "displayName": "Cutoff",
        "key": "cutoffDate",
        "required": false,
        "type": "double"
       }
      ]
     },
     "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
     "type": "filter"
    },
    {
     "attribute": "ubntRadioDistance",
     "label": "Distance",
     "nodeId": "$node",
     "resourceId": "ubntRadioEntry[1]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Options",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirMaxNoAck",
       "label": "AP",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirMaxEnabl",
       "label": "AP",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntWlStatHideSSID",
       "label": "AS",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirMaxGpsSync",
       "label": "GpsSync",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirSelEnabl",
       "label": "AS",
       "nodeId": "$node",
       "resourceId": "ubntAirSelEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirMaxTdd",
       "label": "TDD",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntWlStatWdsEnabl",
       "label": "WDS",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntRadioDfsEnabl",
       "label": "DFS",
       "nodeId": "$node",
       "resourceId": "ubntRadioEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntWlStatApRep",
       "label": "AP",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signals",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntWlStatSignal",
       "label": "Strength",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntWlStatNoisFloor",
       "label": "Noise Floor",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntWlStatRssi",
       "label": "Receive Signal Strength",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioTxPower",
       "label": "Transmit Power",
       "nodeId": "$node",
       "resourceId": "ubntRadioEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Radio RSSI",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntRadioRssi",
       "label": "RSSI 1.1",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioRssiExt",
       "label": "RSSIExt 1.1",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioRssi",
       "label": "RSSI 1.2",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.2]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioRssiExt",
       "label": "RSSIExt 1.2",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.2]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioRssiMgmt",
       "label": "RSSI MGMT 1.1",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntRadioRssiMgmt",
       "label": "RSSI MGMT 1.2",
       "nodeId": "$node",
       "resourceId": "ubntRadioRssiEntry[1.2]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "AirMax Stats",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirMaxCapacity",
       "label": "Capacity",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntAirMaxQuality",
       "label": "Quality",
       "nodeId": "$node",
       "resourceId": "ubntAirMaxEntry[1]",
       "type": "attribute"
      },
      { "expression": "AirtimeRaw / 10", "label": "Airtime", "type": "expression" },
      {
       "attribute": "ubntWlStatCcq",
       "label": "CCQ",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Memory Stats",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntMemTotal",
       "label": "Total",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      {
       "attribute": "ubntMemFree",
       "label": "Free",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      {
       "attribute": "ubntMemCache",
       "label": "Cache",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      {
       "attribute": "ubntMemBuffer",
       "label": "Buffer",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      { "expression": "Total-Buffer-Free-Cache", "label": "Used", "type": "expression" }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "loadValue",
       "label": "1 Minute",
       "nodeId": "$node",
       "resourceId": "loadEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "loadValue",
       "label": "5 Minute",
       "nodeId": "$node",
       "resourceId": "loadEntry[2]",
       "type": "attribute"
      },
      {
       "attribute": "loadValue",
       "label": "15 Minute",
       "nodeId": "$node",
       "resourceId": "loadEntry[3]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Station Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntWlStatStaCount",
       "label": "Stations",
       "nodeId": "$node",
       "resourceId": "ubntWlStatEntry[1]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntSwapFree",
       "label": "Free",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      {
       "attribute": "ubntSwapTotal",
       "label": "Total",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      { "expression": "Total-Free", "label": "Used", "type": "expression" }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntHostTemperature",
       "label": "Temperature",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "GPS Satelites",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntGpsSatsVis",
       "label": "Visable",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      },
      {
       "attribute": "ubntGpsSatsTrack",
       "label": "Tracked",
       "nodeId": "$node",
       "resourceId": "nodeSnmp[]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "AirSync Utilization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntAirSyncDownUtil",
       "label": "Down",
       "nodeId": "$node",
       "resourceId": "ubntAirSyncEntry[1]",
       "type": "attribute"
      },
      {
       "attribute": "ubntAirSyncUpUtil",
       "label": "Up",
       "nodeId": "$node",
       "resourceId": "ubntAirSyncEntry[1]",
       "type": "attribute"
      }
     ]
    }
   ]
  },
  {
   "title": "Station List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signals",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaLocalCINR",
       "label": "Local CINR",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      {
       "attribute": "ubntStaSignal",
       "label": "Signal",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      {
       "attribute": "ubntStaNoiseFloor",
       "label": "Noise Floor",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "In / Out transfered bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaRxBytes",
       "label": "Received",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      {
       "attribute": "ubntStaTxBytes",
       "label": "Transmitted",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "In / Out Capacities",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaRxCapacity",
       "label": "Receive",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      {
       "attribute": "ubntStaTxCapacity",
       "label": "Transmit",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Distance",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
     "format": "lengthm",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaDistance",
       "label": "Distance",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "AirMax Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 2, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "30000000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaAmc",
       "label": "Capacity",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      {
       "attribute": "ubntStaAmq",
       "label": "Quality",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      },
      { "expression": "CCQraw / 10", "label": "CCQ", "type": "expression" }
     ]
    },
    {
     "title": "Uplink Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaTxLatency",
       "label": "Latency",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "AirTime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      { "expression": "Transmitraw / 10", "label": "Transmit", "type": "expression" },
      { "expression": "Receiveraw / 10", "label": "Receive", "type": "expression" }
     ]
    },
    {
     "title": "Connection Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "filter": {
        "backend": "Java",
        "canonicalName": "org.opennms.netmgt.measurements.filters.impl.Chomp",
        "description": "Strips leading and trailing rows that contain nothing but NaNs/null values.",
        "name": "Chomp",
        "parameter": [
         {
          "default": "true",
          "description": "When set, leading and trailing rows containing NaNs will be removed",
          "displayName": "Strip",
          "key": "stripNaNs",
          "required": false,
          "type": "boolean"
         },
         {
          "default": "0",
          "description": "Timestamp in milliseconds. Any rows before this time will be removed.",
          "displayName": "Cutoff",
          "key": "cutoffDate",
          "required": false,
          "type": "double"
         }
        ]
       },
       "filterParameters": { "cutoffDate": "300000", "stripNaNs": "true" },
       "type": "filter"
      },
      {
       "attribute": "ubntStaConnTime",
       "label": "ConnectionTime",
       "nodeId": "$node",
       "resourceId": "$station",
       "type": "attribute"
      }
     ]
    }
   ]
  }
 ]
}